stages:

  data_split:
    cmd: python -m imdb_review_classifier.pipelines.data_split --path_to_config=configs/baseline.yaml
    deps:
    - data/raw/imdb_dataset.csv
    - imdb_review_classifier/pipelines/data_split.py
    params:
      - configs/baseline.yaml:
        - base
        - data_split
    outs:
    - data/split/test.csv
    - data/split/train.csv

  features:
    cmd: python -m imdb_review_classifier.pipelines.featurize --path_to_config=configs/baseline.yaml
    deps:
    - data/split/train.csv
    - imdb_review_classifier/pipelines/featurize.py
    params:
      - configs/baseline.yaml:
        - data_split
        - features
    outs:
    - data/features/train
    - models/count_vectorizer

  train:
    cmd: python -m imdb_review_classifier.pipelines.train --path_to_config=configs/baseline.yaml
    deps:
      - imdb_review_classifier/pipelines/train.py
      - "data/features/train"
    params:
      - configs/baseline.yaml:
          - features
          - base
          - train
    outs:
      - models/lin_reg

  evaluate:
    cmd: python -m imdb_review_classifier.pipelines.evaluate --path_to_config=configs/baseline.yaml
    deps:
      - imdb_review_classifier/pipelines/evaluate.py
      - "data/split/test.csv"
      - "models/count_vectorizer"
      - "models/lin_reg"
    params:
      - configs/baseline.yaml:
          - features
          - train
          - evaluate
    metrics:
    - report/metrics/metrics.json
    plots:
    - report/metrics/cm.csv