stages:

  data_split:
    cmd: python imdb_review_classifier/pipelines/data_split.py --path_to_config=configs/baseline.yaml
    deps:
    - data/raw/imdb_dataset.csv
    - imdb_review_classifier/pipelines/data_split.py
    params:
      - configs/baseline.yaml:
        - base
        - data_split
    outs:
    - data/split/test.csv
    - data/split/train.csv

  features:
    cmd: python imdb_review_classifier/pipelines/featurize.py --path_to_config=configs/baseline.yaml
    deps:
    - data/split/train.csv
    - imdb_review_classifier/pipelines/featurize.py
    params:
      - configs/baseline.yaml:
        - data_split
        - features
    outs:
    - data/features/train
    - models/count_vectorizer
