vars:
  - configs/baseline.yaml

stages:

  data_split:
    desc: Этап разбиения данных на train/test
    cmd: >-
      python -m imdb_review_classifier.pipelines.data_split
      --path_to_config=configs/baseline.yaml
    deps:
      - ${data_split.raw_data}
      - imdb_review_classifier/pipelines/data_split.py
    params:
      - configs/baseline.yaml:
          - base
          - data_split
    outs:
      - ${data_split.train_path}
      - ${data_split.test_path}

  features:
    desc: Этап генерации признаков или обучение векторизаторов/трансформаторов
    cmd: >-
      python -m imdb_review_classifier.pipelines.featurize 
      --path_to_config=configs/baseline.yaml

    deps:
      - ${data_split.train_path}
      - imdb_review_classifier/pipelines/featurize.py
    params:
      - configs/baseline.yaml:
          - data_split
          - features
    outs:
      - ${features.save.train_data}
      - ${features.save.model_file_name}

  train:
    desc: Этап тренировки моделей на train данных
    cmd: >- 
      python -m imdb_review_classifier.pipelines.train 
      --path_to_config=configs/baseline.yaml
    deps:
      - imdb_review_classifier/pipelines/train.py
      - ${features.save.train_data}
    params:
      - configs/baseline.yaml:
          - features
          - base
          - train
    outs:
      - ${train.save.model_path}

  eval:
    desc: Вычисление скоров
    cmd: >-
        python -m imdb_review_classifier.pipelines.evaluate
        --path_to_config=configs/baseline.yaml
    deps:
      - imdb_review_classifier/pipelines/evaluate.py
      - ${data_split.test_path}
      - ${features.save.model_file_name}
      - ${train.save.model_path}
    params:
      - configs/baseline.yaml:
          - features
          - train
          - evaluate
    metrics:
      - ${evaluate.save.metrics_file}
    plots:
      - ${evaluate.save.confusion_matrix}